# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Dave Robins

FetchContent_Declare(SDL3 GIT_REPOSITORY https://github.com/libsdl-org/SDL.git GIT_TAG release-3.4.10 GIT_SHALLOW TRUE)
set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDL_STATIC ON CACHE BOOL "" FORCE)
set(SDL_TEST_LIBRARY OFF CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(SDL3)
add_library(shark_sdl STATIC "${imgui_SOURCE_DIR}/backends/imgui_impl_sdl3.cpp" "${imgui_SOURCE_DIR}/backends/imgui_impl_sdlrenderer3.cpp")
target_include_directories(shark_sdl PUBLIC "${imgui_SOURCE_DIR}/backends")
target_link_libraries(shark_sdl PUBLIC ${RADSHARK_IMGUI_TARGET} SDL3::SDL3-static)
add_executable(radshark WIN32 app/main.cpp)
if(WIN32)
    enable_language(RC)
    target_sources(radshark PRIVATE assets/radshark.rc)
    target_include_directories(radshark PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/assets")
    # rc.exe reads the ICO indirectly; make an updated image trigger a relink.
    set_source_files_properties(assets/radshark.rc PROPERTIES
        OBJECT_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/assets/radshark.ico")
endif()
target_link_libraries(radshark PRIVATE radshark_gui shark_sdl)
radshark_stage_decoder(radshark)
if(RADSHARK_TEST_ENGINE)
    FetchContent_Declare(imgui_test_engine GIT_REPOSITORY https://github.com/ocornut/imgui_test_engine.git GIT_TAG v1.92.8 GIT_SHALLOW TRUE)
    FetchContent_MakeAvailable(imgui_test_engine)
    set(_ite "${imgui_test_engine_SOURCE_DIR}/imgui_test_engine")
    add_library(shark_test_engine STATIC "${_ite}/imgui_te_context.cpp" "${_ite}/imgui_te_coroutine.cpp"
        "${_ite}/imgui_te_engine.cpp" "${_ite}/imgui_te_exporters.cpp" "${_ite}/imgui_te_perftool.cpp"
        "${_ite}/imgui_te_ui.cpp" "${_ite}/imgui_te_utils.cpp" "${_ite}/imgui_capture_tool.cpp")
    target_include_directories(shark_test_engine PUBLIC "${_ite}")
    target_compile_definitions(shark_test_engine PUBLIC IMGUI_TEST_ENGINE_ENABLE_COROUTINE_STDTHREAD_IMPL=1)
    target_link_libraries(shark_test_engine PUBLIC ${RADSHARK_IMGUI_TARGET})
    target_link_libraries(radshark PRIVATE shark_test_engine)
    target_sources(radshark PRIVATE app/ui_tests.cpp)
    target_compile_definitions(radshark PRIVATE SHARK_SAMPLE_PCAP="${CMAKE_CURRENT_SOURCE_DIR}/tests/data/sample.pcap")
endif()
if(RADSHARK_BUILD_TESTS)
    enable_testing()
    if(WIN32 AND SHARK_PCAP_LIBRARY)
        add_executable(shark_capture_test tests/capture_loopback.cpp)
        target_link_libraries(shark_capture_test PRIVATE radshark_core)
        add_test(NAME shark_loopback COMMAND shark_capture_test)
        set_tests_properties(shark_loopback PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 125)
    endif()
    if(RADSHARK_TEST_ENGINE)
        add_test(NAME shark_ui COMMAND radshark --test)
        set_tests_properties(shark_ui PROPERTIES TIMEOUT 90 WORKING_DIRECTORY "${CMAKE_BINARY_DIR}")
    endif()
endif()
install(TARGETS radshark RUNTIME DESTINATION .)
install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE" "${CMAKE_CURRENT_SOURCE_DIR}/THIRD_PARTY.md" DESTINATION .)
if(EXISTS "${RADSHARK_SERVER_DIST}")
    install(DIRECTORY "${RADSHARK_SERVER_DIST}/" DESTINATION wirespy)
endif()
