# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Dave Robins

option(VSPYSHARK_WITH_PCAP "Support standard Ethernet interfaces with libpcap/Npcap" ON)
option(VSPYSHARK_WITH_ICSNEO "Support Intrepid devices with libicsneo" ON)
option(VSPYSHARK_ICSNEO_EXTERNAL_LINKAGE "Embedding executable supplies libicsneo libraries" OFF)
set(VSPYSHARK_NPCAP_SDK "$ENV{NPCAP_SDK}" CACHE PATH "Npcap SDK directory")
set(VSPYSHARK_ICSNEO_INCLUDE "" CACHE PATH "libicsneo include directory")
set(VSPYSHARK_ICSNEO_LIBRARY "" CACHE FILEPATH "libicsneocpp static library")
set(VSPYSHARK_ICSNEO_DEPENDENCIES "" CACHE STRING "libicsneo dependency libraries (semicolon separated)")
add_library(vspyshark_core STATIC src/capture.cpp src/sources/file_source.cpp src/sources/live_source.cpp src/sources/icsneo_source.cpp)
target_include_directories(vspyshark_core PUBLIC src)
target_link_libraries(vspyshark_core PUBLIC wirespy_client)
if(VSPYSHARK_WITH_PCAP)
    find_path(SHARK_PCAP_INCLUDE pcap.h HINTS "${VSPYSHARK_NPCAP_SDK}/Include" "C:/npcap-sdk/Include")
    find_library(SHARK_PCAP_LIBRARY NAMES pcap wpcap HINTS "${VSPYSHARK_NPCAP_SDK}/Lib/x64" "C:/npcap-sdk/Lib/x64")
    if(SHARK_PCAP_INCLUDE AND SHARK_PCAP_LIBRARY)
        target_compile_definitions(vspyshark_core PRIVATE VSPYSHARK_HAVE_PCAP)
        target_include_directories(vspyshark_core PRIVATE "${SHARK_PCAP_INCLUDE}")
        target_link_libraries(vspyshark_core PUBLIC "${SHARK_PCAP_LIBRARY}")
        message(STATUS "VSpy Shark: standard Ethernet capture enabled")
    else()
        message(WARNING "Npcap/libpcap SDK not found: interface capture unavailable")
    endif()
endif()
if(VSPYSHARK_WITH_ICSNEO)
    if(EXISTS "${VSPYSHARK_ICSNEO_INCLUDE}/icsneo/icsneocpp.h" AND EXISTS "${VSPYSHARK_ICSNEO_LIBRARY}")
        target_compile_definitions(vspyshark_core PRIVATE VSPYSHARK_HAVE_ICSNEO)
        target_include_directories(vspyshark_core PRIVATE "${VSPYSHARK_ICSNEO_INCLUDE}")
        if(NOT VSPYSHARK_ICSNEO_EXTERNAL_LINKAGE)
            target_link_libraries(vspyshark_core PUBLIC "${VSPYSHARK_ICSNEO_LIBRARY}" ${VSPYSHARK_ICSNEO_DEPENDENCIES})
        endif()
        if(WIN32)
            target_link_libraries(vspyshark_core PUBLIC setupapi iphlpapi crypt32 bcrypt dbghelp shlwapi)
        endif()
        message(STATUS "VSpy Shark: libicsneo device capture enabled")
    else()
        message(WARNING "libicsneo not configured: device capture unavailable; set VSPYSHARK_ICSNEO_INCLUDE and VSPYSHARK_ICSNEO_LIBRARY")
    endif()
endif()
